"""remove unique parameter for parent_id of category

Revision ID: e834457d5750
Revises: 571911374698
Create Date: 2019-05-27 18:25:32.692303

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e834457d5750'
down_revision = '571911374698'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('ix_category_parent_id', table_name='category')
    op.create_index(op.f('ix_category_parent_id'), 'category', ['parent_id'], unique=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_category_parent_id'), table_name='category')
    op.create_index('ix_category_parent_id', 'category', ['parent_id'], unique=1)
    # ### end Alembic commands ###
